"use client";

import { motion } from "framer-motion";
import { useState } from "react";
import { Zap, Sparkles, RefreshCw, Globe, Maximize2, ArrowRight, Copy, Check } from "lucide-react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { generatePromptSchema } from "@/lib/validations/schemas";
import type { z } from "zod";
import { cn } from "@/lib/utils";
import { AI_MODEL_LABELS, type AIModel } from "@/types";

type FormData = z.infer<typeof generatePromptSchema>;

const actionOptions = [
  { value: "generate", label: "✨ Generate", desc: "Create a new prompt from your idea" },
  { value: "improve", label: "🚀 Improve", desc: "Make your existing prompt better" },
  { value: "rewrite", label: "🔄 Rewrite", desc: "Rewrite in a different style" },
  { value: "optimize", label: "⚡ Optimize", desc: "Optimize for better AI output" },
  { value: "expand", label: "📝 Expand", desc: "Add more detail and context" },
  { value: "translate", label: "🌍 Translate", desc: "Translate to another language" },
] as const;

export default function GeneratePage() {
  const [result, setResult] = useState("");
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  const { register, handleSubmit, watch, setValue, formState: { errors } } = useForm<FormData>({
    resolver: zodResolver(generatePromptSchema),
    defaultValues: { action: "generate" },
  });

  const selectedAction = watch("action");

  const onSubmit = async (data: FormData) => {
    setLoading(true);
    setResult("");

    // Simulate AI generation (replace with real OpenAI/Gemini API call)
    await new Promise((r) => setTimeout(r, 2000));

    const templates: Record<string, string> = {
      generate: `You are a ${data.aiModel || "ChatGPT"} prompt engineering expert. Based on the idea: "${data.idea}"

Here is a professionally engineered prompt:

---

**Role:** Act as a world-class expert in [relevant field]

**Context:** [Provide specific background and constraints]

**Task:** ${data.idea}

**Format Requirements:**
- Clear and structured output
- Step-by-step breakdown where applicable
- Professional tone

**Quality Standards:**
- Be specific, not generic
- Use technical terminology appropriately
- Consider edge cases and nuances

**Output:** Provide a comprehensive response that covers all aspects of the topic, ensuring accuracy and actionable insights.

---
*Optimized for ${data.aiModel || "ChatGPT"} · Generated by InstaPromptHub AI*`,
      improve: `Here is an improved version of your prompt with enhanced clarity and specificity:\n\n${data.idea}\n\n**Improvements made:**\n• Added specific role definition\n• Included output format requirements\n• Added quality constraints\n• Improved context specification`,
      rewrite: `**Rewritten Prompt:**\n\n${data.idea}\n\n*Rewritten with clearer instructions, better structure, and more specific output requirements for superior AI performance.*`,
      optimize: `**Optimized Prompt:**\n\n${data.idea}\n\n**Optimization notes:**\n• Reduced ambiguity\n• Added specific output format\n• Included success criteria\n• Removed redundant instructions`,
      expand: `**Expanded Prompt:**\n\n${data.idea}\n\n**Additional context added:**\n• Target audience considerations\n• Specific use case scenarios\n• Quality benchmarks\n• Edge case handling\n• Example outputs for reference`,
      translate: `**Translated Prompt (${data.targetLanguage || "Spanish"}):**\n\n${data.idea}\n\n[Translated version would appear here based on your selected language]`,
    };

    setResult(templates[data.action] || templates.generate);
    setLoading(false);
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(result);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="min-h-screen py-16">
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-12"
        >
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass border border-purple-500/20 text-purple-300 text-sm mb-4">
            <Zap className="w-4 h-4" />
            AI-Powered Generator
          </div>
          <h1 className="section-heading text-white mb-4">
            Generate <span className="gradient-text">Perfect Prompts</span>
          </h1>
          <p className="text-white/50 text-lg max-w-xl mx-auto">
            Transform your rough ideas into professionally engineered AI prompts in seconds.
          </p>
        </motion.div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Input Panel */}
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.1 }}
          >
            <form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
              {/* Action Selector */}
              <div className="glass-card rounded-2xl p-5">
                <p className="text-xs font-semibold text-white/50 uppercase tracking-wider mb-3">What do you want to do?</p>
                <div className="grid grid-cols-2 gap-2">
                  {actionOptions.map((action) => (
                    <button
                      key={action.value}
                      type="button"
                      onClick={() => setValue("action", action.value)}
                      className={cn(
                        "p-3 rounded-xl text-left transition-all border",
                        selectedAction === action.value
                          ? "bg-purple-500/20 border-purple-500/40 text-purple-300"
                          : "bg-white/3 border-white/8 text-white/50 hover:text-white hover:border-white/20"
                      )}
                    >
                      <div className="text-sm font-medium">{action.label}</div>
                      <div className="text-[11px] text-white/30 mt-0.5 leading-tight">{action.desc}</div>
                    </button>
                  ))}
                </div>
              </div>

              {/* AI Model */}
              <div className="glass-card rounded-2xl p-5">
                <label className="text-xs font-semibold text-white/50 uppercase tracking-wider mb-3 block">
                  Target AI Model
                </label>
                <div className="grid grid-cols-3 gap-2">
                  {(Object.entries(AI_MODEL_LABELS) as [AIModel, string][]).slice(0, 6).map(([key, label]) => (
                    <button
                      key={key}
                      type="button"
                      onClick={() => setValue("aiModel", key)}
                      className={cn(
                        "px-3 py-2 rounded-lg text-xs font-medium border transition-all",
                        watch("aiModel") === key
                          ? "bg-purple-500/20 border-purple-500/40 text-purple-300"
                          : "bg-white/3 border-white/8 text-white/50 hover:text-white hover:border-white/20"
                      )}
                    >
                      {label}
                    </button>
                  ))}
                </div>
              </div>

              {/* Language (for translate) */}
              {selectedAction === "translate" && (
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: "auto" }}
                  className="glass-card rounded-2xl p-5"
                >
                  <label className="text-xs font-semibold text-white/50 uppercase tracking-wider mb-3 block">
                    Target Language
                  </label>
                  <div className="flex flex-wrap gap-2">
                    {["Tamil", "Hindi", "Spanish", "French", "German", "Japanese", "Chinese"].map((lang) => (
                      <button
                        key={lang} type="button"
                        onClick={() => setValue("targetLanguage", lang)}
                        className={cn(
                          "px-3 py-1.5 rounded-lg text-xs font-medium border transition-all",
                          watch("targetLanguage") === lang
                            ? "bg-purple-500/20 border-purple-500/40 text-purple-300"
                            : "bg-white/3 border-white/8 text-white/50 hover:text-white"
                        )}
                      >{lang}</button>
                    ))}
                  </div>
                </motion.div>
              )}

              {/* Idea Input */}
              <div className="glass-card rounded-2xl p-5">
                <label className="text-xs font-semibold text-white/50 uppercase tracking-wider mb-3 block">
                  {selectedAction === "generate" ? "Describe your idea" : "Enter your prompt"}
                </label>
                <textarea
                  {...register("idea")}
                  rows={6}
                  placeholder={
                    selectedAction === "generate"
                      ? "E.g., I want a prompt that creates a professional LinkedIn bio for a software engineer with 5 years of experience..."
                      : "Paste your existing prompt here..."
                  }
                  className="w-full bg-white/3 border border-white/8 rounded-xl px-4 py-3 text-white placeholder-white/25 text-sm outline-none focus:border-purple-500/40 resize-none leading-relaxed"
                />
                {errors.idea && (
                  <p className="text-xs text-red-400 mt-1.5">{errors.idea.message}</p>
                )}
              </div>

              {/* Submit */}
              <motion.button
                type="submit"
                disabled={loading}
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                className={cn(
                  "w-full py-4 rounded-2xl font-semibold text-white flex items-center justify-center gap-2.5 transition-all",
                  loading
                    ? "bg-white/10 cursor-not-allowed"
                    : "bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-500 hover:to-pink-500 shadow-lg shadow-purple-500/25"
                )}
              >
                {loading ? (
                  <>
                    <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Sparkles className="w-5 h-5" />
                    Generate Prompt
                    <ArrowRight className="w-5 h-5" />
                  </>
                )}
              </motion.button>
            </form>
          </motion.div>

          {/* Output Panel */}
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.2 }}
            className="space-y-4"
          >
            <div className="glass-card rounded-2xl p-5 min-h-[500px] flex flex-col">
              <div className="flex items-center justify-between mb-4">
                <h2 className="font-bold text-white flex items-center gap-2">
                  <Sparkles className="w-5 h-5 text-purple-400" />
                  Generated Prompt
                </h2>
                {result && (
                  <div className="flex items-center gap-2">
                    <button onClick={handleCopy}
                      className={cn("flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all",
                        copied ? "bg-green-500/20 text-green-400 border border-green-500/30" : "bg-white/5 text-white/60 border border-white/10 hover:text-white hover:border-white/20"
                      )}>
                      {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                      {copied ? "Copied!" : "Copy"}
                    </button>
                  </div>
                )}
              </div>

              {result ? (
                <div className="flex-1 overflow-auto">
                  <pre className="whitespace-pre-wrap text-sm text-white/75 leading-relaxed font-mono">
                    {result}
                  </pre>
                </div>
              ) : loading ? (
                <div className="flex-1 flex flex-col items-center justify-center gap-4">
                  <div className="relative">
                    <div className="w-16 h-16 border-2 border-purple-500/20 border-t-purple-500 rounded-full animate-spin" />
                    <Sparkles className="w-6 h-6 text-purple-400 absolute inset-0 m-auto" />
                  </div>
                  <div className="text-center">
                    <p className="text-white/60 font-medium">AI is crafting your prompt...</p>
                    <p className="text-white/30 text-sm mt-1">This usually takes 2-3 seconds</p>
                  </div>
                  <div className="flex flex-col gap-2 w-full mt-4">
                    {[...Array(4)].map((_, i) => (
                      <div key={i} className={`h-3 rounded-full shimmer bg-white/5 ${i === 3 ? "w-2/3" : "w-full"}`} />
                    ))}
                  </div>
                </div>
              ) : (
                <div className="flex-1 flex flex-col items-center justify-center gap-4 text-center">
                  <div className="w-16 h-16 rounded-2xl bg-purple-500/10 flex items-center justify-center">
                    <Zap className="w-8 h-8 text-purple-400" />
                  </div>
                  <div>
                    <p className="text-white/60 font-medium">Your generated prompt will appear here</p>
                    <p className="text-white/30 text-sm mt-1">Describe your idea and click Generate</p>
                  </div>
                  <div className="flex gap-2 text-xs text-white/20">
                    <Globe className="w-3.5 h-3.5" /> Supports 14+ AI models
                    <Maximize2 className="w-3.5 h-3.5 ml-2" /> Unlimited generations
                    <RefreshCw className="w-3.5 h-3.5 ml-2" /> Remix & improve
                  </div>
                </div>
              )}
            </div>

            {result && (
              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className="glass-card rounded-2xl p-4 flex items-center justify-between"
              >
                <p className="text-sm text-white/60">Happy with this prompt?</p>
                <button className="flex items-center gap-2 px-4 py-2 rounded-xl bg-gradient-to-r from-purple-600 to-pink-600 text-white text-sm font-semibold hover:from-purple-500 hover:to-pink-500 transition-all">
                  <Sparkles className="w-4 h-4" />
                  Share it
                </button>
              </motion.div>
            )}
          </motion.div>
        </div>
      </div>
    </div>
  );
}
